### ISSUE TITLE
implement an ontology (submission) status icons

### ISSUE THREAD

**Issue by syphax-bouazzouni** [ontoportal-lirmm/bioportal_web_ui#340]
### Details

Currently, we are showing an ontology  its status by text on the ontology submission page, see the screenshot below 
<img width="709" alt="image" src="https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/29259906/dc7692c3-b026-4f70-9f53-eceb7faf91e5">

The request for this issue is to change this with systems of icons, one in green for parsed successfully, one in red for error in parsing, and one in orange for archived.

I got the inspiration from GitHub Actions,
<img width="709" alt="image" src="https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/29259906/7b4af861-afd0-4c78-8068-bd7934dbce43">
 

### TODO

- [x] Find icons, for the three statuses:  parsed successfully in green, one in red for error in parsing, and one in orange for archived.
- [x] Create a component to display this, with a preview in the lookbook
- [x] When hovering those icons, it's displayed as a popover of the full status text details. (use the existent component tooltip for this )
- [x] Use this icon in the submission table
- [x] Use this icon in front of the name of each ontology on the browse page.

**Comment by syphax-bouazzouni** [comment]
Done #345 


![Image](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/29259906/9517d3f5-3aaf-48ae-8f7d-982fce003b10)
