### ISSUE TITLE
Remove JQuery validate 

### ISSUE THREAD

**Issue by syphax-bouazzouni** [ontoportal-lirmm/bioportal_web_ui#408]
In  the code we can see that we import jquery validate, searching in the code for   `= javascript_include_tag "//ajax.aspnetcdn.com/ajax/jquery.validate/1.11.1/jquery.validate.min.js"`, we can see that its imported  3 times  
<img width="1198" alt="image" src="https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/29259906/20088553-68b5-4592-9381-d9a7fb67eaa4">

## TODO

- [x] See in what it is used 
- [x] If used remove it's usage or replace it with native JS code (or Stimulus) 
- [x] Remove JQuery validate imports

**Comment by syphax-bouazzouni** [comment]
Done in https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/410
