### ISSUE TITLE
Migrate the old JS to a modern frontend JS

### ISSUE THREAD

**Issue by syphax-bouazzouni** [ontoportal-lirmm/bioportal_web_ui#426]
### Context

In release 2.7.0 , we did major work on migrating some old JS code to either a new native JS code or converting it to Ruby, harmonizing and modernizing our code base.

Which makes us more of a ruby project 
![Image](https://github.com/ontoportal-lirmm/ontologies_linked_data/assets/29259906/ee28b972-c845-49e6-b975-732bd9347faf)

than before  
![Image](https://github.com/ontoportal-lirmm/ontologies_linked_data/assets/29259906/fc5d0338-7bff-4278-a0ba-4e1a6119647f)

But still, we, have not yet fully migrated,  below are listed our current  dependencies that we need to remove or update 

From `vendor.js ` (external dependencies)
```ruby 
//= require jquery2
//= require jquery-migrate-1.3.0.min
//= require jquery_ujs
//= require jquery-ui
//= require popper
//= require bootstrap-sprockets 
//= require jquery.dataTables 
//= require chosen.jquery  //removed  ✅
//= require autocomplete
//= require alertify 
//= require jquery.readyselector
//= require trumbowyg
//= require jquery.tooltip //removed  ✅ 
//= require Chart.min  
//= require select2  //removed  ✅ 
//= require jquery.hoverIntent //removed  ✅ 
//= require jquery.simple.tree //removed  ✅ 
//= require jquery.scrollTo-1.4.0-min //removed  ✅ 
//= require jquery.rating.pack //removed  ✅ 
//= require history/jquery.history  //removed  ✅ 
//= require ajax-chosen //removed  ✅ 
//= require jquery.cookie //removed  ✅ 
//= require jquery.blockUI //removed  ✅ 
//= require facebox  //removed  ✅ 
//= require thickbox //removed  ✅ 
//= require fg.menu //removed  ✅ 
//= require jquery.tools.min //removed  ✅ 
//= require dataTables.fixedHeader //removed  ✅ 

```
From `application.js` (our old js code)
```ruby 
//= require bioportal
//= require admin/licenses
//= require bp_ajax_controller  //removed  ✅
//= require bp_notes //removed  ✅ 
//= require bp_form_complete
//= require bp_mappings  //removed  ✅ 
//= require bp_admin
//= require concepts
//= require_tree ./helpers //removed  ✅ 
//= require_tree ./components //removed  ✅ 
//= require projects
//= require application_esbuild
//= require bp_reviews //removed  ✅ 
//= require bp_ontolobridge //removed  ✅ 
//= require bp_analytics //removed  ✅ 
//= require bp_search //removed  ✅ 
//= require bp_recommender //removed  ✅ 
//= require bp_property_tree //removed  ✅ 
//= require home //removed  ✅ 
customElements.define('data-table-loader', DataTableLoader ); //removed  ✅ 
customElements.define('data-table', DataTable ); //removed  ✅ 
customElements.define('instances-table', InstancesTable ); //removed  ✅ 
```

### TODO

- [ ] See the usage of these dependencies,
- [ ] Remove the unused 
- [ ] Migrate the used

**Comment by syphax-bouazzouni** [comment]
The first easy iteration done here https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/429

**Comment by syphax-bouazzouni** [comment]
The second iteration done here https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/307

**Comment by syphax-bouazzouni** [comment]
The fourth iteration done here https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/431

**Comment by syphax-bouazzouni** [comment]
The 5th iteration done here #412

**Comment by syphax-bouazzouni** [comment]
The 6th iteration done here https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/433

**Comment by syphax-bouazzouni** [comment]
The 7th removed the instance JS code here #550

**Comment by syphax-bouazzouni** [comment]
Removed  `bp_mapping.js`  file in  https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/733

**Comment by syphax-bouazzouni** [comment]
Remoded chosen dependency in https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/734

**Comment by syphax-bouazzouni** [comment]
This are things remaining to remove/migrate, @Bilelkihal do you think you can migrate to esbuild the following: datatables, alertify (used in admin page) and trumbowyg (not really used but can be useful in the futur) ?
 ```ruby 
// application.js file 
//= require bioportal
//= require admin/licenses
//= require bp_ajax_controller
//= require bp_notes
//= require bp_form_complete
//= require bp_admin
//= require concepts
//= require projects
//= require Chart.min
//= require application_esbuild

// vendor.js file
// Jquery 2 dependencies
//= require jquery2
//= require jquery-migrate-1.3.0.min
//= require jquery_ujs
//= require jquery-ui
// popper is required by bootstrap 4
//= require popper
//= require bootstrap-sprockets
// Other
//= require jquery.dataTables
//= require autocomplete
// Alertify is used the admin page
//= require alertify
//= require jquery.readyselector
// can be removed used only in the ontology bridge form
//= require trumbowyg
 
```

**Comment by Bilelkihal** [comment]
@syphax-bouazzouni 
For:
- Alertify there are some alternatives like: SweetAlert2 (https://github.com/carlweis/sweetalert2-rails) or we can do something simple custom using a stimulus controller.
- Trumbowyg: We can delete it for now and the day we need it we can use something like Quilljs (https://github.com/abhinavmathur/quilljs-rails)

The real challenge is in datatables since we use it in many parts of the app, and I couldn't find any alternatives with the same features that doesn't require jquery.

**Comment by syphax-bouazzouni** [comment]
> @syphax-bouazzouni For:
> 
>     * Alertify there are some alternatives like: SweetAlert2 (https://github.com/carlweis/sweetalert2-rails) or we can do something simple custom using a stimulus controller.
> 
>     * Trumbowyg: We can delete it for now and the day we need it we can use something like Quilljs (https://github.com/abhinavmathur/quilljs-rails)
> 
> 
> The real challenge is in datatables since we use it in many parts of the app, and I couldn't find any alternatives with the same features that doesn't require jquery.

- Ok for Trumbowyg, but need to find its usage and remove it, see screenshot bellow 
- For Alertify, no need to change it, you need to just to migrate to work in esbuild. (adding it in the package.json and having a dedicated stimulus controller or use https://www.stimulus-components.com/docs/stimulus-dialog) 
- For Datatable, same no to need to change, just make it work using esbuild, I think you started already the work with the stimulus controller` table_component_controller.js`, you need just to migrate  the remaining usage of the old datatable code, see screenshot bellow 
![image](https://github.com/user-attachments/assets/8397b519-78ac-4dc3-971e-8fd0a5a0ac7a)

**Comment by syphax-bouazzouni** [comment]
Removed `bp_ajax_controller.js` in https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/821

**Comment by imadbourouche** [comment]
2026 roadmap
