### ISSUE TITLE
add https to stageportal

### ISSUE THREAD

**Issue by syphax-bouazzouni** [ontoportal-lirmm/bioportal_web_ui#60]
How to :

-  https://www.rosehosting.com/blog/how-to-install-lets-encrypt-with-apache-on-centos-7/
- https://ontoportal.github.io/administration/steps/enable_https/

Done. : https://stageportal.lirmm.fr/

**Comment by syphax-bouazzouni** [comment]
Is it that simple ? i need to see if there not cause hidden bugs behind this change simple  change
For know i add the https only for the UI ( and i have done it because its need for implementing the self hosted outline wiki that woks only overs https)

**Comment by jonquet** [comment]
Yes. Switch to HTTPS is a  requirements we had several times.
Need to put STI-RX in the loop.
Automate the process of generating the certificates and get certificates for all the URL (see this with STI-RX).

**Comment by syphax-bouazzouni** [comment]
It's not that simple, bugs : 

- Users can't connect

**Comment by syphax-bouazzouni** [comment]
HTTPs was removed from stageportal

**Comment by syphax-bouazzouni** [comment]
# 2023 retry 


### TODO

- [ ] HTTPS for the API
- [ ] HTTPS for the UI
- [ ] HTTPS for the SPARQL
- [ ] HTTPS for the SERVICES

### How to 
From https://ontoportal.github.io/administration/administration/steps/enable_https

1- Install certificates 

```
certbot --apache -d stageportal.lirmm.fr -d data.stageportal.lirmm.fr -d services.stageportal.lirmm.fr -d sparql.stageportal.lirmm.fr
``` 

2- Clean /etc/httpd/conf.d/10-appliance.ontoportal.org_non-tls.conf to redirect to HTTPS
3 - Add the following for each reverse proxy in /etc/httpd/conf.d/10-appliance.ontoportal.org_non-tls-le-ssl.conf
``` 
SSLProxyEngine on
```

3- Add certs keys to /etc/nginx/sites-enabled/ontologies_api.conf
4- Update the config files of UI, API, and fairness

### Change the lines in /config/environments/appliance.rb

$REST_URL_PREFIX = "https://#{[$REST_HOSTNAME, $REST_PORT].compact.join(':')}/"

### Change the lines in /fairness/src/main/resources/config/portals/agroportal/config.properties (same for stageportal and bioportal)
url=https://data.agroportal.lirmm.fr

### Change the lines in  /config/bioportal_config_appliance.rb

$UI_URL = "https://#{$UI_HOSTNAME}"
$REST_URL ||= "https://#{[$REST_HOSTNAME, $REST_PORT].compact.join(':')}"
$ANNOTATOR_URL = $PROXY_URL = "https://services.#{$HOSTNAME}/annotator"
$NCBO_ANNOTATOR_URL = "https://services.#{$HOSTNAME}/ncbo_annotatorplus"
$FAIRNESS_URL  = "https://services.stageportal.lirmm.fr/ofaire/"

5- Deploy code
