### ISSUE TITLE
New Group and Categories UI 

### ISSUE THREAD

**Issue by syphax-bouazzouni** [ontoportal-lirmm/bioportal_web_ui#726]
### TODO

- [x] https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/618
- [x] New Groups UIs
![image](https://github.com/user-attachments/assets/c6801986-0082-42ab-85f2-a3a4c31ad7db)

- [x] New Categories UIs
![image](https://github.com/user-attachments/assets/bfc2034a-599b-4863-ba0f-d072d3c2d6d5)

- [x] Update categories form to accept URIs and parentCategory

- [ ] Create UNESCO categories

**Comment by syphax-bouazzouni** [comment]
Done in https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/736
