### ISSUE TITLE
Refactor concept Details page

### ISSUE THREAD

**Issue by syphax-bouazzouni** [ontoportal-lirmm/bioportal_web_ui#86]
## Use case
http://stageportal.lirmm.fr/ontologies/TOP/?p=classes&conceptid=https%3A%2F%2Fopentheso.cefe.cnrs.fr%2Fopentheso%2F%3Fidc%3D238%26idt%3Dth9

<img  alt="image" src="https://user-images.githubusercontent.com/29259906/177528576-14a02d96-56ef-4db4-b6a4-bf1e91e7b301.png">

## Todo

- [x] Separate on two blocks the mapped attributes with the rest 
- [x] Interpret HTML links in  the property "definitions" (may use  markdown)
- [x] Thinks to use html_safe for the rest (not mapped attributes)
- [x] Aviod information repetition

**Comment by syphax-bouazzouni** [comment]
realated https://github.com/agroportal/project-management/issues/31

**Comment by jonquet** [comment]
related to https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/1#issuecomment-1290469218
As this will be certainly implemented on the same Tab in the UI.

**Comment by jonquet** [comment]
Related to SKOS-XL implementation too as we want to refactor the way URI values are display in this UI using a small block

**Comment by jonquet** [comment]
Discussion today with 2 main approaches identified: 

1. Three blocks: (i) mapped (to the model) properties; (ii) all other unmapped properties with no duplication of the mapped ones; (iii) turtle colored and indented block. Note block (i) and (ii) can be merged as there is no duplications. The mouse over on the mapped properties names may provide an explanation such as "Defined as XX by AgroPortal and YY in source file"

2. Three blocks: (i) mapped properties; (ii)  all the unmapped properties including the mapped ones; (iii) the same block than above.

@syphax-bouazzouni and @jonquet understand each other ;)
